# Generated by Django 4.0.3 on 2022-04-16 13:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_post_about_author'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='rating_of_author',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='post',
            name='rating_of_post',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
